[2025-03-27T04:13:44.944+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T04:13:44.974+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T04:13:44.991+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T04:13:44.992+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 6
[2025-03-27T04:13:45.020+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_store> on 2025-03-02 00:00:00+00:00
[2025-03-27T04:13:45.032+0000] {standard_task_runner.py:72} INFO - Started process 212 to run task
[2025-03-27T04:13:45.041+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'construction_web_scraping_v01', 'scrape_and_store', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/construction_web_scraping.py', '--cfg-path', '/tmp/tmp5xccg4pn']
[2025-03-27T04:13:45.052+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask scrape_and_store
[2025-03-27T04:13:45.152+0000] {task_command.py:467} INFO - Running <TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [running]> on host c79bd584e644
[2025-03-27T04:13:45.323+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='waiyong' AIRFLOW_CTX_DAG_ID='construction_web_scraping_v01' AIRFLOW_CTX_TASK_ID='scrape_and_store' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-27T04:13:45.331+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T04:13:45.371+0000] {logging_mixin.py:190} INFO - Scraping page 1...
[2025-03-27T04:13:59.944+0000] {logging_mixin.py:190} INFO - Scraping page 2...
[2025-03-27T04:14:15.924+0000] {logging_mixin.py:190} INFO - Scraping page 3...
[2025-03-27T04:14:35.523+0000] {logging_mixin.py:190} INFO - Scraping page 4...
[2025-03-27T04:14:51.260+0000] {logging_mixin.py:190} INFO - Scraping page 5...
[2025-03-27T04:15:04.733+0000] {logging_mixin.py:190} INFO - Columns before rename: ['BIL.', 'KOD PROJEK', 'PEMAJU', 'PROJEK', 'NO. PERMIT', 'STATUS PROJEK KESELURUHAN', 'RINGKASAN PROJEK', 'Daerah Projek', 'Negeri Projek', 'Harga Minimum (RM)', 'Harga Maksimum (RM)']
[2025-03-27T04:15:04.755+0000] {logging_mixin.py:190} INFO -   Bil  ...                                  RINGKASAN PROJEK
0   1  ...  https://teduh.kpkt.gov.my/project-swasta/30969-1
1   2  ...  https://teduh.kpkt.gov.my/project-swasta/30946-1
2   3  ...  https://teduh.kpkt.gov.my/project-swasta/30937-1
3   4  ...  https://teduh.kpkt.gov.my/project-swasta/30921-1
4   5  ...  https://teduh.kpkt.gov.my/project-swasta/30920-1
5   6  ...  https://teduh.kpkt.gov.my/project-swasta/30914-1
6   7  ...  https://teduh.kpkt.gov.my/project-swasta/30913-1
7   8  ...  https://teduh.kpkt.gov.my/project-swasta/30909-1
8   9  ...  https://teduh.kpkt.gov.my/project-swasta/30908-1
9  10  ...  https://teduh.kpkt.gov.my/project-swasta/30902-1

[10 rows x 11 columns]
[2025-03-27T04:15:04.781+0000] {logging_mixin.py:190} INFO - SQL dump created: /tmp/teduh_dump.sql
[2025-03-27T04:15:04.783+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 255, in run_scraper
    client = create_minio_client()
NameError: name 'create_minio_client' is not defined
[2025-03-27T04:15:04.801+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=construction_web_scraping_v01, task_id=scrape_and_store, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250327T041344, end_date=20250327T041504
[2025-03-27T04:15:04.842+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T04:15:04.844+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task scrape_and_store (name 'create_minio_client' is not defined; 212)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 255, in run_scraper
    client = create_minio_client()
NameError: name 'create_minio_client' is not defined
[2025-03-27T04:15:04.896+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T04:15:04.918+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T04:15:04.923+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-27T04:36:11.123+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T04:36:11.144+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T04:36:11.153+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T04:36:11.155+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 7
[2025-03-27T04:36:11.173+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_store> on 2025-03-02 00:00:00+00:00
[2025-03-27T04:36:11.179+0000] {standard_task_runner.py:72} INFO - Started process 806 to run task
[2025-03-27T04:36:11.183+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'construction_web_scraping_v01', 'scrape_and_store', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/construction_web_scraping.py', '--cfg-path', '/tmp/tmpulh5rd3x']
[2025-03-27T04:36:11.187+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask scrape_and_store
[2025-03-27T04:36:11.269+0000] {task_command.py:467} INFO - Running <TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [running]> on host c79bd584e644
[2025-03-27T04:36:11.423+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='waiyong' AIRFLOW_CTX_DAG_ID='construction_web_scraping_v01' AIRFLOW_CTX_TASK_ID='scrape_and_store' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-27T04:36:11.425+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T04:36:11.450+0000] {logging_mixin.py:190} INFO - Scraping page 1...
[2025-03-27T04:36:24.818+0000] {logging_mixin.py:190} INFO - Scraping page 2...
[2025-03-27T04:36:39.762+0000] {logging_mixin.py:190} INFO - Scraping page 3...
[2025-03-27T04:36:58.980+0000] {logging_mixin.py:190} INFO - Scraping page 4...
[2025-03-27T04:37:12.924+0000] {logging_mixin.py:190} INFO - Scraping page 5...
[2025-03-27T04:37:27.224+0000] {logging_mixin.py:190} INFO - Columns before rename: ['BIL.', 'KOD PROJEK', 'PEMAJU', 'PROJEK', 'NO. PERMIT', 'STATUS PROJEK KESELURUHAN', 'RINGKASAN PROJEK', 'Daerah Projek', 'Negeri Projek', 'Harga Minimum (RM)', 'Harga Maksimum (RM)']
[2025-03-27T04:37:27.243+0000] {logging_mixin.py:190} INFO -   Bil  ...                                  RINGKASAN PROJEK
0   1  ...  https://teduh.kpkt.gov.my/project-swasta/30969-1
1   2  ...  https://teduh.kpkt.gov.my/project-swasta/30946-1
2   3  ...  https://teduh.kpkt.gov.my/project-swasta/30937-1
3   4  ...  https://teduh.kpkt.gov.my/project-swasta/30921-1
4   5  ...  https://teduh.kpkt.gov.my/project-swasta/30920-1
5   6  ...  https://teduh.kpkt.gov.my/project-swasta/30914-1
6   7  ...  https://teduh.kpkt.gov.my/project-swasta/30913-1
7   8  ...  https://teduh.kpkt.gov.my/project-swasta/30909-1
8   9  ...  https://teduh.kpkt.gov.my/project-swasta/30908-1
9  10  ...  https://teduh.kpkt.gov.my/project-swasta/30902-1

[10 rows x 11 columns]
[2025-03-27T04:37:27.276+0000] {logging_mixin.py:190} INFO - SQL dump created: /tmp/teduh_dump.sql
[2025-03-27T04:37:27.279+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e62fb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /construction-web-scraping?location=
[2025-03-27T04:37:27.682+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e62290>: Failed to establish a new connection: [Errno 111] Connection refused')': /construction-web-scraping?location=
[2025-03-27T04:37:28.485+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e621d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /construction-web-scraping?location=
[2025-03-27T04:37:30.089+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e62110>: Failed to establish a new connection: [Errno 111] Connection refused')': /construction-web-scraping?location=
[2025-03-27T04:37:33.292+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e63bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /construction-web-scraping?location=
[2025-03-27T04:37:33.295+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fca68e63700>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 266, in run_scraper
    found = client.bucket_exists(MINIO_BUCKET)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 662, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 413, in _execute
    region = self._get_region(bucket_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 470, in _get_region
    response = self._url_open(
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 279, in _url_open
    response = self._http.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /construction-web-scraping?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e63700>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-27T04:37:33.328+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=construction_web_scraping_v01, task_id=scrape_and_store, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250327T043611, end_date=20250327T043733
[2025-03-27T04:37:33.365+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T04:37:33.367+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task scrape_and_store (HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /construction-web-scraping?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e63700>: Failed to establish a new connection: [Errno 111] Connection refused')); 806)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fca68e63700>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 266, in run_scraper
    found = client.bucket_exists(MINIO_BUCKET)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 662, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 413, in _execute
    region = self._get_region(bucket_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 470, in _get_region
    response = self._url_open(
  File "/home/airflow/.local/lib/python3.10/site-packages/minio/api.py", line 279, in _url_open
    response = self._http.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /construction-web-scraping?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca68e63700>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-27T04:37:33.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T04:37:33.434+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T04:37:33.437+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-27T05:57:28.202+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T05:57:28.225+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T05:57:28.237+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T05:57:28.238+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 7
[2025-03-27T05:57:28.255+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_store> on 2025-03-02 00:00:00+00:00
[2025-03-27T05:57:28.260+0000] {standard_task_runner.py:72} INFO - Started process 2779 to run task
[2025-03-27T05:57:28.265+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'construction_web_scraping_v01', 'scrape_and_store', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/construction_web_scraping.py', '--cfg-path', '/tmp/tmppnrctye1']
[2025-03-27T05:57:28.268+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask scrape_and_store
[2025-03-27T05:57:28.331+0000] {task_command.py:467} INFO - Running <TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [running]> on host c79bd584e644
[2025-03-27T05:57:28.426+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='waiyong' AIRFLOW_CTX_DAG_ID='construction_web_scraping_v01' AIRFLOW_CTX_TASK_ID='scrape_and_store' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-27T05:57:28.428+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T05:57:28.445+0000] {logging_mixin.py:190} INFO - Scraping page 1...
[2025-03-27T05:57:44.775+0000] {logging_mixin.py:190} INFO - Columns before rename: ['BIL.', 'KOD PROJEK', 'PEMAJU', 'PROJEK', 'NO. PERMIT', 'STATUS PROJEK KESELURUHAN', 'RINGKASAN PROJEK', 'Daerah Projek', 'Negeri Projek', 'Harga Minimum (RM)', 'Harga Maksimum (RM)']
[2025-03-27T05:57:44.794+0000] {logging_mixin.py:190} INFO -   Bil  ...                                  RINGKASAN PROJEK
0   1  ...  https://teduh.kpkt.gov.my/project-swasta/30969-1
1   2  ...  https://teduh.kpkt.gov.my/project-swasta/30946-1
2   3  ...  https://teduh.kpkt.gov.my/project-swasta/30937-1
3   4  ...  https://teduh.kpkt.gov.my/project-swasta/30921-1
4   5  ...  https://teduh.kpkt.gov.my/project-swasta/30920-1
5   6  ...  https://teduh.kpkt.gov.my/project-swasta/30914-1
6   7  ...  https://teduh.kpkt.gov.my/project-swasta/30913-1
7   8  ...  https://teduh.kpkt.gov.my/project-swasta/30909-1
8   9  ...  https://teduh.kpkt.gov.my/project-swasta/30908-1
9  10  ...  https://teduh.kpkt.gov.my/project-swasta/30902-1

[10 rows x 11 columns]
[2025-03-27T05:57:44.799+0000] {logging_mixin.py:190} INFO - CSV file created: /tmp/teduh_dump.csv
[2025-03-27T05:57:44.863+0000] {logging_mixin.py:190} INFO - Uploaded /tmp/teduh_dump.csv to minio://construction-web-scraping/teduh/teduh_dump.csv
[2025-03-27T05:57:44.864+0000] {logging_mixin.py:190} INFO - Scraping and upload done!
[2025-03-27T05:57:44.866+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T05:57:44.878+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T05:57:44.880+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=construction_web_scraping_v01, task_id=scrape_and_store, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250327T055728, end_date=20250327T055744
[2025-03-27T05:57:44.957+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T05:57:44.973+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-27T06:15:20.568+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T06:15:20.588+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T06:15:20.599+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T06:15:20.600+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 7
[2025-03-27T06:15:20.619+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_store> on 2025-03-02 00:00:00+00:00
[2025-03-27T06:15:20.625+0000] {standard_task_runner.py:72} INFO - Started process 3303 to run task
[2025-03-27T06:15:20.629+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'construction_web_scraping_v01', 'scrape_and_store', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/construction_web_scraping.py', '--cfg-path', '/tmp/tmpyvrg313e']
[2025-03-27T06:15:20.633+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask scrape_and_store
[2025-03-27T06:15:20.697+0000] {task_command.py:467} INFO - Running <TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [running]> on host c79bd584e644
[2025-03-27T06:15:20.837+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='waiyong' AIRFLOW_CTX_DAG_ID='construction_web_scraping_v01' AIRFLOW_CTX_TASK_ID='scrape_and_store' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-27T06:15:20.839+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T06:15:20.867+0000] {logging_mixin.py:190} INFO - Scraping page 1...
[2025-03-27T06:15:37.089+0000] {logging_mixin.py:190} INFO - Columns before rename: ['BIL.', 'KOD PROJEK', 'PEMAJU', 'PROJEK', 'NO. PERMIT', 'STATUS PROJEK KESELURUHAN', 'RINGKASAN PROJEK', 'Daerah Projek', 'Negeri Projek', 'Harga Minimum (RM)', 'Harga Maksimum (RM)']
[2025-03-27T06:15:37.134+0000] {logging_mixin.py:190} INFO -   Bil  ...                                  RINGKASAN PROJEK
0   1  ...  https://teduh.kpkt.gov.my/project-swasta/30969-1
1   2  ...  https://teduh.kpkt.gov.my/project-swasta/30946-1
2   3  ...  https://teduh.kpkt.gov.my/project-swasta/30937-1
3   4  ...  https://teduh.kpkt.gov.my/project-swasta/30921-1
4   5  ...  https://teduh.kpkt.gov.my/project-swasta/30920-1
5   6  ...  https://teduh.kpkt.gov.my/project-swasta/30914-1
6   7  ...  https://teduh.kpkt.gov.my/project-swasta/30913-1
7   8  ...  https://teduh.kpkt.gov.my/project-swasta/30909-1
8   9  ...  https://teduh.kpkt.gov.my/project-swasta/30908-1
9  10  ...  https://teduh.kpkt.gov.my/project-swasta/30902-1

[10 rows x 11 columns]
[2025-03-27T06:15:37.141+0000] {logging_mixin.py:190} INFO - CSV file created: /tmp/construction_20250327.csv
[2025-03-27T06:15:37.161+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 257, in run_scraper
    object_name=MINIO_OBJECT,
NameError: name 'MINIO_OBJECT' is not defined
[2025-03-27T06:15:37.182+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=construction_web_scraping_v01, task_id=scrape_and_store, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250327T061520, end_date=20250327T061537
[2025-03-27T06:15:37.223+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T06:15:37.224+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 46 for task scrape_and_store (name 'MINIO_OBJECT' is not defined; 3303)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 257, in run_scraper
    object_name=MINIO_OBJECT,
NameError: name 'MINIO_OBJECT' is not defined
[2025-03-27T06:15:37.257+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T06:15:37.280+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T06:15:37.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-27T06:39:21.759+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T06:39:21.804+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T06:39:21.823+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-27T06:39:21.824+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 6
[2025-03-27T06:39:21.854+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_store> on 2025-03-02 00:00:00+00:00
[2025-03-27T06:39:21.866+0000] {standard_task_runner.py:72} INFO - Started process 4115 to run task
[2025-03-27T06:39:21.873+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'construction_web_scraping_v01', 'scrape_and_store', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/construction_web_scraping.py', '--cfg-path', '/tmp/tmpje0bjpy8']
[2025-03-27T06:39:21.879+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask scrape_and_store
[2025-03-27T06:39:21.987+0000] {task_command.py:467} INFO - Running <TaskInstance: construction_web_scraping_v01.scrape_and_store scheduled__2025-03-02T00:00:00+00:00 [running]> on host c79bd584e644
[2025-03-27T06:39:22.237+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='waiyong' AIRFLOW_CTX_DAG_ID='construction_web_scraping_v01' AIRFLOW_CTX_TASK_ID='scrape_and_store' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-27T06:39:22.241+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T06:39:22.265+0000] {logging_mixin.py:190} INFO - Scraping page 1...
[2025-03-27T06:39:39.590+0000] {logging_mixin.py:190} INFO - Scraping page 2...
[2025-03-27T06:39:56.935+0000] {logging_mixin.py:190} INFO - Scraping page 3...
[2025-03-27T06:40:19.287+0000] {logging_mixin.py:190} INFO - Scraping page 4...
[2025-03-27T06:40:36.265+0000] {logging_mixin.py:190} INFO - Scraping page 5...
[2025-03-27T06:40:52.883+0000] {logging_mixin.py:190} INFO - Scraping page 6...
[2025-03-27T06:41:09.691+0000] {logging_mixin.py:190} INFO - Scraping page 7...
[2025-03-27T06:41:27.311+0000] {logging_mixin.py:190} INFO - Scraping page 8...
[2025-03-27T06:41:44.170+0000] {logging_mixin.py:190} INFO - Scraping page 9...
[2025-03-27T06:42:04.221+0000] {logging_mixin.py:190} INFO - Scraping page 10...
[2025-03-27T06:42:21.026+0000] {logging_mixin.py:190} INFO - Scraping page 11...
[2025-03-27T06:42:38.319+0000] {logging_mixin.py:190} INFO - Scraping page 12...
[2025-03-27T06:42:55.276+0000] {logging_mixin.py:190} INFO - Scraping page 13...
[2025-03-27T06:43:12.527+0000] {logging_mixin.py:190} INFO - Scraping page 14...
[2025-03-27T06:43:28.466+0000] {logging_mixin.py:190} INFO - Scraping page 15...
[2025-03-27T06:43:44.731+0000] {logging_mixin.py:190} INFO - Scraping page 16...
[2025-03-27T06:44:01.399+0000] {logging_mixin.py:190} INFO - Scraping page 17...
[2025-03-27T06:44:18.931+0000] {logging_mixin.py:190} INFO - Scraping page 18...
[2025-03-27T06:44:37.129+0000] {logging_mixin.py:190} INFO - Scraping page 19...
[2025-03-27T06:44:57.307+0000] {logging_mixin.py:190} INFO - Scraping page 20...
[2025-03-27T06:45:13.441+0000] {logging_mixin.py:190} INFO - Scraping page 21...
[2025-03-27T06:45:31.670+0000] {logging_mixin.py:190} INFO - Scraping page 22...
[2025-03-27T06:45:48.954+0000] {logging_mixin.py:190} INFO - Scraping page 23...
[2025-03-27T06:46:06.296+0000] {logging_mixin.py:190} INFO - Scraping page 24...
[2025-03-27T06:46:24.028+0000] {logging_mixin.py:190} INFO - Scraping page 25...
[2025-03-27T06:46:39.947+0000] {logging_mixin.py:190} INFO - Scraping page 26...
[2025-03-27T06:46:58.664+0000] {logging_mixin.py:190} INFO - Scraping page 27...
[2025-03-27T06:47:18.693+0000] {logging_mixin.py:190} INFO - Scraping page 28...
[2025-03-27T06:47:38.031+0000] {logging_mixin.py:190} INFO - Scraping page 29...
[2025-03-27T06:47:54.317+0000] {logging_mixin.py:190} INFO - Scraping page 30...
[2025-03-27T06:48:09.110+0000] {logging_mixin.py:190} INFO - Scraping page 31...
[2025-03-27T06:48:24.991+0000] {logging_mixin.py:190} INFO - Scraping page 32...
[2025-03-27T06:48:47.272+0000] {logging_mixin.py:190} INFO - Error scraping https://teduh.kpkt.gov.my/project-swasta/30060-1: HTTPSConnectionPool(host='teduh.kpkt.gov.my', port=443): Max retries exceeded with url: /project-swasta/30060-1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fca681f0d90>, 'Connection to teduh.kpkt.gov.my timed out. (connect timeout=10)'))
[2025-03-27T06:48:51.599+0000] {logging_mixin.py:190} INFO - Scraping page 33...
[2025-03-27T06:49:14.105+0000] {logging_mixin.py:190} INFO - Scraping page 34...
[2025-03-27T06:49:33.073+0000] {logging_mixin.py:190} INFO - Scraping page 35...
[2025-03-27T06:49:49.552+0000] {logging_mixin.py:190} INFO - Scraping page 36...
[2025-03-27T06:50:07.562+0000] {logging_mixin.py:190} INFO - Scraping page 37...
[2025-03-27T06:50:25.944+0000] {logging_mixin.py:190} INFO - Scraping page 38...
[2025-03-27T06:50:44.506+0000] {logging_mixin.py:190} INFO - Scraping page 39...
[2025-03-27T06:51:02.018+0000] {logging_mixin.py:190} INFO - Scraping page 40...
[2025-03-27T06:51:20.470+0000] {logging_mixin.py:190} INFO - Scraping page 41...
[2025-03-27T06:51:39.169+0000] {logging_mixin.py:190} INFO - Scraping page 42...
[2025-03-27T06:51:58.653+0000] {logging_mixin.py:190} INFO - Scraping page 43...
[2025-03-27T06:52:16.712+0000] {logging_mixin.py:190} INFO - Scraping page 44...
[2025-03-27T06:52:33.409+0000] {logging_mixin.py:190} INFO - Scraping page 45...
[2025-03-27T06:52:52.472+0000] {logging_mixin.py:190} INFO - Scraping page 46...
[2025-03-27T06:53:09.715+0000] {logging_mixin.py:190} INFO - Scraping page 47...
[2025-03-27T06:53:27.195+0000] {logging_mixin.py:190} INFO - Scraping page 48...
[2025-03-27T06:53:44.832+0000] {logging_mixin.py:190} INFO - Scraping page 49...
[2025-03-27T06:54:01.830+0000] {logging_mixin.py:190} INFO - Scraping page 50...
[2025-03-27T06:54:20.283+0000] {logging_mixin.py:190} INFO - Scraping page 51...
[2025-03-27T06:54:37.146+0000] {logging_mixin.py:190} INFO - Scraping page 52...
[2025-03-27T06:54:53.554+0000] {logging_mixin.py:190} INFO - Scraping page 53...
[2025-03-27T06:55:10.046+0000] {logging_mixin.py:190} INFO - Scraping page 54...
[2025-03-27T06:55:29.516+0000] {logging_mixin.py:190} INFO - Scraping page 55...
[2025-03-27T06:55:46.524+0000] {logging_mixin.py:190} INFO - Scraping page 56...
[2025-03-27T06:56:02.783+0000] {logging_mixin.py:190} INFO - Scraping page 57...
[2025-03-27T06:56:21.684+0000] {logging_mixin.py:190} INFO - Scraping page 58...
[2025-03-27T06:56:38.081+0000] {logging_mixin.py:190} INFO - Scraping page 59...
[2025-03-27T06:56:55.065+0000] {logging_mixin.py:190} INFO - Scraping page 60...
[2025-03-27T06:57:15.554+0000] {logging_mixin.py:190} INFO - Scraping page 61...
[2025-03-27T06:57:31.951+0000] {logging_mixin.py:190} INFO - Scraping page 62...
[2025-03-27T06:57:49.160+0000] {logging_mixin.py:190} INFO - Scraping page 63...
[2025-03-27T06:58:08.684+0000] {logging_mixin.py:190} INFO - Scraping page 64...
[2025-03-27T06:58:26.178+0000] {logging_mixin.py:190} INFO - Scraping page 65...
[2025-03-27T06:58:42.042+0000] {logging_mixin.py:190} INFO - Scraping page 66...
[2025-03-27T06:59:04.289+0000] {logging_mixin.py:190} INFO - Error scraping https://teduh.kpkt.gov.my/project-swasta/19795-1: HTTPSConnectionPool(host='teduh.kpkt.gov.my', port=443): Max retries exceeded with url: /project-swasta/19795-1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fca680ea140>, 'Connection to teduh.kpkt.gov.my timed out. (connect timeout=10)'))
[2025-03-27T06:59:11.819+0000] {logging_mixin.py:190} INFO - Scraping page 67...
[2025-03-27T06:59:30.088+0000] {logging_mixin.py:190} INFO - Scraping page 68...
[2025-03-27T06:59:47.113+0000] {logging_mixin.py:190} INFO - Scraping page 69...
[2025-03-27T07:00:04.143+0000] {logging_mixin.py:190} INFO - Scraping page 70...
[2025-03-27T07:00:24.180+0000] {logging_mixin.py:190} INFO - Scraping page 71...
[2025-03-27T07:00:41.548+0000] {logging_mixin.py:190} INFO - Scraping page 72...
[2025-03-27T07:01:00.831+0000] {logging_mixin.py:190} INFO - Scraping page 73...
[2025-03-27T07:01:16.781+0000] {logging_mixin.py:190} INFO - Scraping page 74...
[2025-03-27T07:01:36.137+0000] {logging_mixin.py:190} INFO - Scraping page 75...
[2025-03-27T07:01:54.914+0000] {logging_mixin.py:190} INFO - Error scraping https://teduh.kpkt.gov.my/project-swasta/19691-1: HTTPSConnectionPool(host='teduh.kpkt.gov.my', port=443): Max retries exceeded with url: /project-swasta/19691-1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fca686179a0>, 'Connection to teduh.kpkt.gov.my timed out. (connect timeout=10)'))
[2025-03-27T07:02:02.471+0000] {logging_mixin.py:190} INFO - Scraping page 76...
[2025-03-27T07:02:18.968+0000] {logging_mixin.py:190} INFO - Scraping page 77...
[2025-03-27T07:02:35.166+0000] {logging_mixin.py:190} INFO - Scraping page 78...
[2025-03-27T07:02:56.146+0000] {logging_mixin.py:190} INFO - Scraping page 79...
[2025-03-27T07:03:13.849+0000] {logging_mixin.py:190} INFO - Scraping page 80...
[2025-03-27T07:03:30.692+0000] {logging_mixin.py:190} INFO - Scraping page 81...
[2025-03-27T07:03:51.070+0000] {logging_mixin.py:190} INFO - Scraping page 82...
[2025-03-27T07:04:09.454+0000] {logging_mixin.py:190} INFO - Scraping page 83...
[2025-03-27T07:04:30.938+0000] {logging_mixin.py:190} INFO - Scraping page 84...
[2025-03-27T07:04:54.851+0000] {logging_mixin.py:190} INFO - Scraping page 85...
[2025-03-27T07:05:12.784+0000] {logging_mixin.py:190} INFO - Scraping page 86...
[2025-03-27T07:05:30.931+0000] {logging_mixin.py:190} INFO - Scraping page 87...
[2025-03-27T07:05:47.494+0000] {logging_mixin.py:190} INFO - Scraping page 88...
[2025-03-27T07:06:06.588+0000] {logging_mixin.py:190} INFO - Scraping page 89...
[2025-03-27T07:06:24.227+0000] {logging_mixin.py:190} INFO - Scraping page 90...
[2025-03-27T07:06:40.831+0000] {logging_mixin.py:190} INFO - Scraping page 91...
[2025-03-27T07:06:58.786+0000] {logging_mixin.py:190} INFO - Scraping page 92...
[2025-03-27T07:07:17.378+0000] {logging_mixin.py:190} INFO - Scraping page 93...
[2025-03-27T07:07:33.737+0000] {logging_mixin.py:190} INFO - Scraping page 94...
[2025-03-27T07:07:50.350+0000] {logging_mixin.py:190} INFO - Scraping page 95...
[2025-03-27T07:08:10.394+0000] {logging_mixin.py:190} INFO - Scraping page 96...
[2025-03-27T07:08:31.649+0000] {logging_mixin.py:190} INFO - Scraping page 97...
[2025-03-27T07:08:47.378+0000] {logging_mixin.py:190} INFO - Scraping page 98...
[2025-03-27T07:09:05.621+0000] {logging_mixin.py:190} INFO - Scraping page 99...
[2025-03-27T07:09:21.723+0000] {logging_mixin.py:190} INFO - Scraping page 100...
[2025-03-27T07:09:22.146+0000] {timeout.py:68} ERROR - Process timed out, PID: 4115
[2025-03-27T07:09:22.164+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/construction_web_scraping.py", line 172, in run_scraper
    current_headers, rows = scrape_page(page_number)
  File "/opt/airflow/dags/construction_web_scraping.py", line 131, in scrape_page
    response = requests.get(url)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 717, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 4115
[2025-03-27T07:09:22.188+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=construction_web_scraping_v01, task_id=scrape_and_store, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250327T063921, end_date=20250327T070922
[2025-03-27T07:09:22.230+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T07:09:22.279+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 2
[2025-03-27T07:09:22.321+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T07:09:22.325+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
